In [1]:
import pandas as pd
import numpy as np
import statistics as st

In [3]:
df = pd.read_csv("C:\\Users\\paart\\Downloads\\movies_initial\\movies_initial.csv")

In [4]:
df

,imdbID,title,year,rating,runtime,genre,released,director,writer,cast,...,imdbRating,imdbVotes,poster,plot,fullplot,language,country,awards,lastupdated,type
0,1,Carmencita,1894,NOT RATED,1 min,"Documentary, Short",NaN,William K.L. Dickson,NaN,Carmencita,...,5.9,1032.0,https://m.media-amazon.com/images/M/MV5BMjAzND...,Performing on what looks like a small wooden s...,Performing on what looks like a small wooden s...,NaN,USA,NaN,2015-08-26 00:03:45.040000000,movie
1,5,Blacksmith Scene,1893,UNRATED,1 min,Short,1893-05-09,William K.L. Dickson,NaN,"Charles Kayser, John Ott",...,6.2,1189.0,NaN,Three men hammer on an anvil and pass a bottle...,A stationary camera looks at a large anvil wit...,NaN,USA,1 win.,2015-08-26 00:03:50.133000000,movie
2,3,Pauvre Pierrot,1892,NaN,4 min,"Animation, Comedy, Short",1892-10-28,�mile Reynaud,NaN,NaN,...,6.7,566.0,NaN,"One night, Arlequin come to see his lover Colo...","One night, Arlequin come to see his lover Colo...",NaN,France,NaN,2015-08-12 00:06:02.720000000,movie
3,8,Edison Kinetoscopic Record of a Sneeze,1894,NaN,1 min,"Documentary, Short",1894-01-09,William K.L. Dickson,NaN,Fred Ott,...,5.9,988.0,NaN,A man (Thomas Edison's assistant) takes a pinc...,A man (Edison's assistant) takes a pinch of sn...,NaN,USA,NaN,2015-08-10 00:21:07.127000000,movie
4,10,Employees Leaving the Lumi�re Factory,1895,NaN,1 min,"Documentary, Short",1895-03-22,Louis Lumi�re,NaN,NaN,...,6.9,3469.0,NaN,A man opens the big gates to the Lumi�re facto...,A man opens the big gates to the Lumi�re facto...,NaN,France,NaN,2015-08-26 00:03:56.603000000,movie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46009,5005684,The New Classmate,2015,NaN,NaN,"Drama, Family",2015-10-11,Ashwiny Iyer Tiwari,NaN,"Swara Bhaskar, Ratna Pathak, Pankaj Tripathy",...,NaN,NaN,NaN,NaN,NaN,Hindi,India,NaN,2015-09-10 22:28:58.883000000,movie
46010,5013056,Untitled Christopher Nolan Project,2017,NaN,NaN,Sci-Fi,2017-07-21,Christopher Nolan,"Christopher Nolan (screenplay), Christopher Nolan",NaN,...,NaN,NaN,NaN,Plot is being kept under wraps.,Plot is being kept under wraps.,English,"USA, UK",NaN,2015-09-11 17:15:04.527000000,movie
46011,5013980,Die Turnschuh-Giganten,2016,NaN,NaN,"Biography, Drama, War",NaN,Oliver Dommenget,Christian Schnalke,"Ken Duken, Florian Bartholom�i, Torben Liebrec...",...,NaN,NaN,NaN,NaN,NaN,German,Germany,NaN,2015-09-12 23:13:48.997000000,movie
46012,5016760,The Monster of Mangatiti,2015,NaN,NaN,NaN,2015-09-06,NaN,John Banas,"Greta Gregory, Mark Mitchinson, Flynn Allan, H...",...,NaN,NaN,NaN,Heather Walsh tells her story of the time she ...,Heather Walsh tells her story of the time she ...,English,New Zealand,NaN,2015-09-12 03:47:27.780000000,movie
46013,5023260,The Last Word,2016,NaN,NaN,Comedy,NaN,Mark Pellington,NaN,Amanda Seyfried,...,NaN,NaN,NaN,NaN,NaN,English,USA,NaN,2015-09-15 18:27:50.240000000,movie

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdbID       46014 non-null  int64
 1   title        46014 non-null  object
 2   year         46014 non-null  object
 3   rating       24629 non-null  object
 4   runtime      43377 non-null  object
 5   genre        45615 non-null  object
 6   released     43002 non-null  object
 7   director     45409 non-null  object
 8   writer       42942 non-null  object
 9   cast         44928 non-null  object
 10  metacritic   9401 non-null   float64
 11  imdbRating   44300 non-null  float64
 12  imdbVotes    44299 non-null  float64
 13  poster       35798 non-null  object
 14  plot         42161 non-null  object
 15  fullplot     41421 non-null  object
 16  language     44899 non-null  object
 17  country      45830 non-null  object
 18  awards       23542 non-null  object
 19  lastupdated  46014 non-null  object
 20  type         45976 non-null  object
dtypes: float64(3), int64(1), object(17)
memory usage: 7.4+ MB

In [6]:
#mean calculation
df.mean()

C:\Users\paart\AppData\Local\Temp\ipykernel_11404\2417271936.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()

imdbID        855206.215456
metacritic        56.896288
imdbRating         6.381454
imdbVotes      11800.552134
dtype: float64

In [10]:
df.mean(axis = 1)[0:5]

C:\Users\paart\AppData\Local\Temp\ipykernel_11404\369270116.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean(axis = 1)[0:5]

0     346.300000
1     400.066667
2     191.900000
3     333.966667
4    1161.966667
dtype: float64

In [11]:
#median
df.median()

C:\Users\paart\AppData\Local\Temp\ipykernel_11404\1739800283.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median()

imdbID        252487.5
metacritic        58.0
imdbRating         6.6
imdbVotes        999.0
dtype: float64

In [12]:
df.median(axis = 1)[0:5]

C:\Users\paart\AppData\Local\Temp\ipykernel_11404\1941941222.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median(axis = 1)[0:5]

0     5.9
1     6.2
2     6.7
3     8.0
4    10.0
dtype: float64

In [13]:
df.mode()

,imdbID,title,year,rating,runtime,genre,released,director,writer,cast,...,imdbRating,imdbVotes,poster,plot,fullplot,language,country,awards,lastupdated,type
0,67919.0,Hamlet,2015,R,90 min,Drama,2015-09-01,John Ford,Woody Allen,Georges M�li�s,...,7.2,76.0,https://m.media-amazon.com/images/M/MV5BMTcwMz...,The plot is unknown at this time.,Plot is unknown.,English,USA,1 nomination.,2015-08-16 00:24:45.463000000,movie
1,69035.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,109.0,https://m.media-amazon.com/images/M/MV5BMTk1ND...,NaN,The plot is unknown at this time.,NaN,NaN,NaN,2015-08-29 00:20:20.843000000,NaN
2,169302.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,https://m.media-amazon.com/images/M/MV5BMTk3Nj...,NaN,The plot is unknown.,NaN,NaN,NaN,NaN,NaN
3,1826550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,https://m.media-amazon.com/images/M/MV5BMjAwMT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,https://m.media-amazon.com/images/M/MV5BOTU5MT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#standard derivation
df.std()

C:\Users\paart\AppData\Local\Temp\ipykernel_11404\454836062.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.std()

imdbID        1.141979e+06
metacritic    1.771537e+01
imdbRating    1.183113e+00
imdbVotes     4.934499e+04
dtype: float64

In [15]:
df.groupby(['year']).mean()

             imdbID  metacritic  imdbRating  imdbVotes
year
1874   3.155794e+06         NaN       6.600     167.00
1880   2.221420e+06         NaN       7.300     326.00
1887   2.075247e+06         NaN       5.100     347.00
1888   1.050838e+06         NaN       6.450     984.50
1890   5.990105e+05         NaN       5.325     395.25
...             ...         ...         ...        ...
2016   3.817759e+06         NaN         NaN        NaN
2016�  3.816466e+06         NaN         NaN        NaN
2017   3.112227e+06         NaN         NaN        NaN
2018   4.680182e+06         NaN         NaN        NaN
2019   4.877122e+06         NaN         NaN        NaN

[170 rows x 4 columns]

In [16]:
df.dropna()

,imdbID,title,year,rating,runtime,genre,released,director,writer,cast,...,imdbRating,imdbVotes,poster,plot,fullplot,language,country,awards,lastupdated,type
432,17136,Metropolis,1927,NOT RATED,153 min,"Drama, Sci-Fi",1927-03-13,Fritz Lang,"Thea von Harbou (screenplay), Thea von Harbou ...","Alfred Abel, Gustav Fr�hlich, Rudolf Klein-Rog...",...,8.3,99845.0,https://m.media-amazon.com/images/M/MV5BNDAzNT...,In a futuristic city sharply divided between t...,"Sometime in the future, the city of Metropolis...",German,Germany,3 wins & 4 nominations.,2015-09-04 00:09:30.553000000,movie
1458,27977,Modern Times,1936,G,87 min,"Comedy, Drama",1936-02-25,Charles Chaplin,Charles Chaplin,"Charles Chaplin, Paulette Goddard, Henry Bergm...",...,8.6,123603.0,https://m.media-amazon.com/images/M/MV5BMjAyMT...,The Tramp struggles to live in modern industri...,"Chaplins last 'silent' film, filled with sound...",English,USA,3 wins & 1 nomination.,2015-09-04 00:06:38.867000000,movie
1624,29453,P�p� le Moko,1937,NOT RATED,94 min,"Crime, Drama, Romance",1941-03-03,Julien Duvivier,"Henri La Barthe (novel), Henri La Barthe (scen...","Jean Gabin, Gabriel Gabrio, Saturnin Fabre, Fe...",...,7.8,4398.0,https://m.media-amazon.com/images/M/MV5BMTY5NT...,P�p� le Moko is a gangster from Paris that hid...,P�p� le Moko is a gangster from Paris that hid...,"French, Arabic",France,2 wins.,2015-09-10 17:45:12.290000000,movie
1675,29843,The Adventures of Robin Hood,1938,PG,102 min,"Action, Adventure, Romance",1938-05-14,"Michael Curtiz, William Keighley",Norman Reilly Raine (original screenplay: base...,"Errol Flynn, Olivia de Havilland, Basil Rathbo...",...,8.0,36789.0,https://m.media-amazon.com/images/M/MV5BMTUxMz...,When Prince John and the Norman Lords begin op...,"Sir Robin of Locksley, defender of downtrodden...",English,USA,Won 3 Oscars. Another 2 wins & 2 nominations.,2015-08-14 00:11:51.833000000,movie
1929,32138,The Wizard of Oz,1939,PASSED,102 min,"Adventure, Family, Fantasy",1939-08-25,"Victor Fleming, George Cukor, Mervyn LeRoy, No...","Noel Langley (screenplay), Florence Ryerson (s...","Judy Garland, Frank Morgan, Ray Bolger, Bert Lahr",...,8.1,262132.0,https://m.media-amazon.com/images/M/MV5BMTU0MT...,Dorothy Gale is swept away to a magical land i...,In this charming film based on the popular L. ...,English,USA,Won 2 Oscars. Another 7 wins & 13 nominations.,2015-09-01 00:29:05.490000000,movie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44708,4009460,Saving Christmas,2014,PG,80 min,"Comedy, Family",2014-11-14,Darren Doane,"Darren Doane, Cheston Hervey","Kirk Cameron, Darren Doane, Bridgette Cameron,...",...,1.6,9744.0,https://m.media-amazon.com/images/M/MV5BMTc3MT...,Kirk is enjoying the annual Christmas party ex...,Kirk is enjoying the annual Christmas party ex...,English,USA,4 wins & 2 nominations.,2015-08-16 00:12:45.527000000,movie
44872,4104022,People Places Things,2015,R,85 min,Comedy,2015-08-14,James C. Strouse,James C. Strouse,"Jemaine Clement, Regina Hall, Jessica Williams...",...,7.0,628.0,https://m.media-amazon.com/images/M/MV5BMTg2Nj...,Will Henry is a newly single graphic novelist ...,PEOPLE PLACES THINGS tells the story of Will H...,English,USA,1 nomination.,2015-08-31 00:01:35.920000000,movie
44947,4145304,Unexpected,2015,R,90 min,"Comedy, Drama",2015-07-24,Kris Swanberg,"Megan Mercier, Kris Swanberg","Cobie Smulders, Anders Holm, Gail Bean, Elizab...",...,5.7,661.0,https://m.media-amazon.com/images/M/MV5BMjM5NT...,An inner-city high school teacher discovers sh...,An inner-city high school teacher discovers sh...,English,USA,1 nomination.,2015-09-06 00:20:02.930000000,movie
45015,4185572,The Hunting Ground,2015,PG-13,103 min,Documentary,2015-01-23,Kirby Dick,Kirby Dick,"Kirby Dick, Amy Ziering, Amy Herdy, Annie Clark",...,6.4,324.0,https://m.media-amazon.com/images/M/MV5BNjc4Mj...,An expos� of rape crimes on U.S. college campu...,From the makers of The Invisible War (2012) co...,English,USA,1 nomination.,2015-08-29 00:23:33.937000000,movie
45092,4229236,Cobain: Montage of Heck,2015,TV-MA,145 min,"Documentary, Biography, Music",2015-05-04,Brett Morgen,Brett Morgen,"Aaron Burckhard, Chad Channing, Don Cobain, Je...",...,7.7,13973.0,https://m.media-amazon.com/images/M/MV5BMjIyOT...,An authorized documentary on the late musician...,An authorized documentary on the late musician...,English,USA,Nominated for 6 Primetime Emmys. Another 1 win.,2015-09-17 04:40:35.987000000,movie